### PR TITLE
Replacing Flatpickr with a native HTML datetime picker

### LINKED ISSUE #27: Poll end date panel broken
https://i.imgur.com/ot6zzze.jpg
Web browser: firefox
Flarum: latest

The list of months doesn't open. Some month names are slightly cropped at the bottom. The year numbers are slightly cropped at the bottom. I can't add a calendar translation to other languages.

### LINKED ISSUE #44: Plugin seems to load "flatpickr.min.css" from external CDN
## Bug Report

**Current Behavior**
Plugin works fine but causes problems (both legal and technical) in environments that strictly prohibit loading external resources. Furthermore the CDN is hosted by Cloudflare with is a privacy concern.

As this seems to be only a small css file, would it be possible to just include it in the distribution instead of downloading it?

Thanks.

### PR DESCRIPTION
**Pull request by rafaucau**
**Resolves #27, resolves #44**

**Changes proposed in this pull request:**

This PR removes Flatpickr and instead uses the HTML datetime picker. This makes the extension more lightweight and the native picker works much better especially on mobile.

Additionally PR updates dependecies and prettier configuration.

**Screenshot**

image

**Confirmed**
- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

**Comment by datitisev** [comment]
Two things

1) It's incredibly hard to review this code because it is mixed with prettier reformats.
2) I don't think we should use the native datepicker, it's not good UX on Firefox even with a pattern attribute. I'd rather keep using `flatpickr` and just lazy load it.

**Comment by rafaucau** [comment]
> It's incredibly hard to review this code because it is mixed with prettier reformats.

@datitisev I removed the commits that changed the prettier config. I will send a new PR that updates config

**Comment by sdebacker** [comment]
> I'm also not in favour of dropping `flatpickr` at this time. As @datitisev says, naitive HTML 5 picker components are poor on Firefox, but non-existent on Safari.

There is a native datepicker on Safari since 14.1.

**Comment by n0099** [comment]
Due to service downgrade of jsdelivr in mainland china: https://github.com/jsdelivr/jsdelivr/issues/18348#issuecomment-997777996, it's now more important to allow user self-host this css instead of requesting from public cdn which is currently unstable in china.

**Pull request closed without merging**
