### PR TITLE
Support calendar translation

### PR DESCRIPTION
**Pull request by luuhai48**
- Support translation for Calendar.
 - Added admin setting **first day of week** for Calendar.

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
What exactly was the intent for this change? Where are we showing months and/or first day of the week? That doesn't seem to belong to this extension (?)

`SettingsModal` has been deprecated in Flarum beta 15 and removed in beta 16, so this will require an update. We can also replace `fof/extend` with Flarum's `Extend\Settings` extender.

Also I'm pretty sure most of these translations are already part of DayJS, so I don't understand why they belong in any extension.

**Comment by datitisev** [comment]
> Where are we showing months and/or first day of the week? That doesn't seem to belong to this extension (?)

Perhaps by the date picker that we use `flatpickr` for.

**Comment by clarkwinkelmann** [comment]
For some reason I had never yet clicked on the end date input :man_facepalming: 

That seems like a lot of code for a feature that might not even be used by all users of the extension. Can we maybe do the same but pull the values from DayJS so we can at least delegate/re-use the actual translation to language packs?

**Comment by datitisev** [comment]
Probably. We also should lazy load the picker 😂

**Comment by Ralkage** [comment]
@clarkwinkelmann how hard would it be to implement the native browser date selector over the current solution? I would very much prefer to use a native solution in the event that flatpickr no longer supported or is abandoned in the future. Not sure if we want to go ahead and close this issue, but at the same time I can also create a feature request/enhancement for the date picker.

**Comment by clarkwinkelmann** [comment]
Last time I checked the date+time native picker still wasn't supported well enough, but I have not checked again recently. It seems that we need the time selection here since it's important based on the timezone.

However testing Polls again it doesn't look like flatpickr is asking me for the time. Actually, I see it shows 10am in the field but can't find to edit it at all. So if it's not working with that library either, it might not be worse to use the native option...

Since we use Carbon in the backend to read the text, we can technically enter the date in another format and it will also work.

In the Terms extension I made the choice to use just a text field, but add a button to auto-fill a default time already formatted https://github.com/FriendsOfFlarum/terms/blob/0.6.2/js/src/admin/components/PolicyEdit.js#L95-L117 but it's not a very good comparison since here we don't want to enter the current time.

Another option could be to have a dropdown with options like "24h", "1 week", and "custom", and if you choose custom, then we show a text field with native input, and maybe a help text that says which format you use if you don't have the picker.

**Comment by davwheat** [comment]
I think, based on Clark's comments, we should switch to an option of presets and a custom input.

I've just made changes to Drafts to remove Flatpickr in favour of date and time inputs, and that seems to work fine. The same could be done here.

**Comment by imorland** [comment]
Closing as appears stale

**Pull request closed without merging**
