### PR TITLE
Fixed CSS for long poll answers

### PR DESCRIPTION
**Pull request by iPurpl3x**

### CODE REVIEW

**Comment by datitisev** [comment]
@iPurpl3x Can you provide a screenshot of how it looks without the style vs with ?

**Comment by luceos** [comment]
@iPurpl3x Rafael, next time make sure to provide at least a description of what this change entails. We're not accepting every PR just because it affects your client.

**Comment by iPurpl3x** [comment]
Sorry I thought that the title would be enough to explaining the changes.
Here are some screenshots :

*before*
before

*after*
before

**Comment by datitisev** [comment]
This fix causes issues with the positioning of the percentage.

image

image

**Comment by iPurpl3x** [comment]
> This fix causes issues with the positioning of the percentage.

Thanks for pointing that out, I'll check this out when I get a moment.

**Comment by KyrneDev** [comment]
@iPurpl3x Have you had any time to take a look at this?

**Comment by iPurpl3x** [comment]
@datitisev I fixed the issue. This was a bit tricky!
image
@KyrneDev sorry for coming back to this only now. For the last months I've been using another GitHub account (for work) and kind of forgot this PR.

**Pull request merged**
