### PR TITLE
Allow voting for multiple options without change perm

### LINKED ISSUE #77: No ability to change permissions to create polls
## Bug Report

**Current Behavior**
After upgrading to version 2.0, I cannot change the permissions to create polls. All options are grayed out.
image

**Environment**
- Flarum version: 1.8.1
- Extension version: 2.0.1
- PHP version: 8.2
- Browser: Chrome 115

### PR DESCRIPTION
**Pull request by dsevillamartin**
**Fixes #77**

**Changes proposed in this pull request:**
- Add 'Vote' button that appears only if vote allows multiple votes & user cannot change vote
- Make help text & vote button sticky to bottom of poll options (to help users not miss it!)
- Add poll option to prevent users from changing votes in poll
- Fix poll creation not saving "hide votes" perm from 926bd7c2fec335c236e6ca0de69fc214fc736019 (#2)

**Reviewers should focus on:**
- Not 100% sure if the sticky works on mobile? The mobile responsive emulator on firefox seemed to ignore it. I don't think it's that big of an issue.
- A potential problem is that navigating to another Flarum page will not alert the user that they never voted. I'm wary of using `onbeforeremove` for this since that could alert potentially in other situations. I believe this could maybe be done altering router? That may be too complicated.

**Screenshot**
image
image
image

**Confirmed**

- [X] Frontend changes: tested on a local Flarum installation.
- [X] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by Wlork** [comment]
Hello @dsevillamartin :)

Looks like a great job, as usual !

However, I have several questions:

- I'm puzzled about fixing the "Vote" button. I understand the idea, but I like to see all options directly before voting.

The height will be adjustable ?
And how it'll work with images ? 

- The button will only appear when there is a multiple choice ? If only one choice is set (with non vote change) is activated, the button will appear too ?

Thank you in advance :)

**Comment by dsevillamartin** [comment]
@Wlork I think a video will answer most of these questions. For the last, the button only appears if it's multiple choice & the user cannot change their vote. This functionality isn't necessary if the user can only select one vote or if they can change votes at any point.


https://github.com/FriendsOfFlarum/polls/assets/6401250/ce881f3c-bdf0-49d6-b84e-b8fbd3a6f522

**Comment by Wlork** [comment]
@dsevillamartin Thank for video :) 

> I think a video will answer most of these questions.

Yes, I confirm, I prefer to have all options directly rather than scrolling.... Perhaps, if possible, an option in Admin to show a part of options or all of options ?

> This functionality isn't necessary if the user can only select one vote or if they can change votes at any point.

OK :+1:  If there is only one choice, there will be the alert at the bottom "You cannot change your vote after voting" ?  I can't see on your screenshot ?

**Comment by dsevillamartin** [comment]
@Wlork Not sure what you mean by have all the options directly? You have to scroll without this PR, and you still do with it. You're just given the info on the poll in advance without needing to reach the bottom first.

> OK 👍 If there is only one choice, there will be the alert at the bottom "You cannot change your vote after voting" ? I can't see on your screenshot ?

If users can only vote for one choice, it will still say that they cannot change their vote.

**Comment by Wlork** [comment]
@dsevillamartin 

> Not sure what you mean by have all the options directly? You have to scroll without this PR, and you still do with it. You're just given the info on the poll in advance without needing to reach the bottom first.

Yes. It may sound crazy, but I prefer scroll down the page and see all options than scroll down a poll  :smile: 
So, if we could choose, that would be great..... If it's not possible, that's fine :) 

> If users can only vote for one choice, it will still say that they cannot change their vote.

:+1:

**Comment by dsevillamartin** [comment]
> Yes. It may sound crazy, but I prefer scroll down the page and see all options than scroll down a poll 😄

I'm not sure what you mean by this. I don't understand where you want the poll options to appear?
I don't have plans on modifying this UI any further, but I'd like to visualize what you're describing.

**Comment by dsevillamartin** [comment]
@Wlork Oh, if you think the poll is now in its own scrollable container - it's not. You still scroll the page to view more options, it's just that the bottom is now affixed to the bottom of the screen until you pass it, so it can show important poll info.

**Comment by Wlork** [comment]
@dsevillamartin 

Oh, right ! 

It wasn't obvious on video, so thanks for the explanation. I'm reassured now :)

**Pull request merged**
